services:
  - type: web
    name: mental-health-chatbot
    env: python
    plan: free
    buildCommand: |
      mkdir -p flask/dist
      cp -r react/dist/* flask/dist/
      cd flask
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    rootDir: flask